[[constraint]]
  name = "github.com/andybalholm/cascadia"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  version = "v1.2"
  name = "github.com/gin-gonic/gin"

[prune]
  go-tests = true
  unused-packages = true
